# Generated by Django 4.0.2 on 2022-02-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_film_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('film_genre', models.IntegerField(choices=[(1, 'horror'), (3, 'drama'), (4, 'comedy'), (0, 'unknown'), (2, 'sci-fi')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.extrainfo'),
        ),
    ]
