# Generated by Django 4.0.2 on 2022-02-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_extrainfo_film_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='film_genre',
            field=models.IntegerField(choices=[(2, 'sci-fi'), (3, 'drama'), (4, 'comedy'), (0, 'unknown'), (1, 'horror')], default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('stars', models.IntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.film')),
            ],
        ),
    ]
