# Generated by Django 4.0.2 on 2022-02-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_extrainfo_film_genre_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='film_genre',
            field=models.IntegerField(choices=[(3, 'drama'), (2, 'sci-fi'), (1, 'horror'), (4, 'comedy'), (0, 'unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.film'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('films', models.ManyToManyField(to='api.Film')),
            ],
        ),
    ]
